In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
cost_f=[]
slopes=[]
intercept=[]
def gradient_descent(x,y):
    m_curr=c_curr=0
    n=len(x)
    iteration=10000
    learning_rate=0.01
    cost_previous=0
    plt.scatter(x,y,color='r',marker='*')
    for i in range(iteration):
        y_predicted=m_curr*x+c_curr
        plt.plot(x,y_predicted,color='g')
        cost=(1/n)*sum(val**2 for val in (y-y_predicted))
        md=-(2/n)*sum((y-y_predicted)*x) #slope: derivative of rss with respect to m
        cd=-(2/n)*sum((y-y_predicted)) # derivative of rss with respect to c
        m_curr=m_curr-learning_rate*md
        c_curr=c_curr-learning_rate*cd
        slopes.append(m_curr)
        intercept.append(c_curr)
        cost_f.append(cost)
        if math.isclose(cost,cost_previous,rel_tol=1e-05):
            break
        cost_previous=cost
        print(f'm:{m_curr}, cost{c_curr}, iterations:{i}')
x=np.array([1,2,3,4,5])
y=np.array([5,7,9,11,13])

In [ ]:
gradient_descent(x,y)

## sgd regressor:- Linar regression withStochastic GD 

In [1]:
from sklearn.linear_model import SGDRegressor,LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
# from sklearn.datasets import load_boston  

In [2]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [3]:
data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [ ]:
target

In [3]:
# spling the data
xtrain,xtest,ytrain,ytest=train_test_split(data,target)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(xtest.shape)

(379, 13)
(127, 13)
(379,)
(127, 13)


In [4]:
# standardization- x ,y
x_scalar=StandardScaler()
y_scalar=StandardScaler()

In [5]:
# convert ytrain to 2d
ytrain=ytrain.reshape(ytrain.shape[0],1) #ytrain.shape[0]=379
ytest=ytest.reshape(ytest.shape[0],1)

In [6]:
print(ytrain.shape)
print(ytest.shape)

(379, 1)
(127, 1)


In [7]:
# standardization- x ,y
xtrain=x_scalar.fit_transform(xtrain)
xtest=x_scalar.transform(xtest)
ytrain=y_scalar.fit_transform(ytrain)
ytest=y_scalar.transform(ytest)

In [8]:
model=SGDRegressor()
model.fit(xtrain,ytrain)

C:\Users\archa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor()

In [9]:
print('train data r square',model.score(xtrain,ytrain))
print('train data r square',model.score(xtest,ytest))

train data r square 0.7652172879933323
train data r square 0.6278005773950468


In [10]:
score=cross_val_score(model,xtrain,ytrain,cv=5)
score

C:\Users\archa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\archa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\archa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\archa\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

array([0.64748279, 0.66988404, 0.73472611, 0.79070092, 0.8126764 ])

In [11]:
np.mean(score)

0.7310940520664527

In [ ]:
# Model2

In [12]:
model2=LinearRegression()
model2.fit(xtrain,ytrain)

LinearRegression()

In [13]:
print('train data r square',model2.score(xtrain,ytrain))
print('train data r square',model2.score(xtest,ytest))

train data r square 0.7707934047821916
train data r square 0.6457874165419215


In [14]:
scores=cross_val_score(model2,xtrain,ytrain,cv=5)
scores

array([0.64751284, 0.69577587, 0.74164078, 0.77972377, 0.82007382])

In [15]:
np.mean(scores)

0.7369454151643945